/**
 * flexcheckin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.Href;
import io.swagger.client.model.IdAndHref;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CheckinSession {
  
  @SerializedName("memberShipValidated")
  private Boolean memberShipValidated = null;
  @SerializedName("teamAccessValidated")
  private Boolean teamAccessValidated = null;
  @SerializedName("organizer")
  private Href organizer = null;
  @SerializedName("ticketTypes")
  private List<IdAndHref> ticketTypes = null;
  @SerializedName("id")
  private String id = null;
  @SerializedName("scannerStation")
  private String scannerStation = null;
  @SerializedName("events")
  private Href events = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getMemberShipValidated() {
    return memberShipValidated;
  }
  public void setMemberShipValidated(Boolean memberShipValidated) {
    this.memberShipValidated = memberShipValidated;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getTeamAccessValidated() {
    return teamAccessValidated;
  }
  public void setTeamAccessValidated(Boolean teamAccessValidated) {
    this.teamAccessValidated = teamAccessValidated;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Href getOrganizer() {
    return organizer;
  }
  public void setOrganizer(Href organizer) {
    this.organizer = organizer;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<IdAndHref> getTicketTypes() {
    return ticketTypes;
  }
  public void setTicketTypes(List<IdAndHref> ticketTypes) {
    this.ticketTypes = ticketTypes;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getScannerStation() {
    return scannerStation;
  }
  public void setScannerStation(String scannerStation) {
    this.scannerStation = scannerStation;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Href getEvents() {
    return events;
  }
  public void setEvents(Href events) {
    this.events = events;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckinSession checkinSession = (CheckinSession) o;
    return (this.memberShipValidated == null ? checkinSession.memberShipValidated == null : this.memberShipValidated.equals(checkinSession.memberShipValidated)) &&
        (this.teamAccessValidated == null ? checkinSession.teamAccessValidated == null : this.teamAccessValidated.equals(checkinSession.teamAccessValidated)) &&
        (this.organizer == null ? checkinSession.organizer == null : this.organizer.equals(checkinSession.organizer)) &&
        (this.ticketTypes == null ? checkinSession.ticketTypes == null : this.ticketTypes.equals(checkinSession.ticketTypes)) &&
        (this.id == null ? checkinSession.id == null : this.id.equals(checkinSession.id)) &&
        (this.scannerStation == null ? checkinSession.scannerStation == null : this.scannerStation.equals(checkinSession.scannerStation)) &&
        (this.events == null ? checkinSession.events == null : this.events.equals(checkinSession.events));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.memberShipValidated == null ? 0: this.memberShipValidated.hashCode());
    result = 31 * result + (this.teamAccessValidated == null ? 0: this.teamAccessValidated.hashCode());
    result = 31 * result + (this.organizer == null ? 0: this.organizer.hashCode());
    result = 31 * result + (this.ticketTypes == null ? 0: this.ticketTypes.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.scannerStation == null ? 0: this.scannerStation.hashCode());
    result = 31 * result + (this.events == null ? 0: this.events.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckinSession {\n");
    
    sb.append("  memberShipValidated: ").append(memberShipValidated).append("\n");
    sb.append("  teamAccessValidated: ").append(teamAccessValidated).append("\n");
    sb.append("  organizer: ").append(organizer).append("\n");
    sb.append("  ticketTypes: ").append(ticketTypes).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  scannerStation: ").append(scannerStation).append("\n");
    sb.append("  events: ").append(events).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
