/**
 * flexcheckin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CreateValidation {
  
  @SerializedName("scannerstationname")
  private String scannerstationname = null;
  @SerializedName("checkinSessionId")
  private String checkinSessionId = null;
  @SerializedName("barcode")
  private String barcode = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getScannerstationname() {
    return scannerstationname;
  }
  public void setScannerstationname(String scannerstationname) {
    this.scannerstationname = scannerstationname;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCheckinSessionId() {
    return checkinSessionId;
  }
  public void setCheckinSessionId(String checkinSessionId) {
    this.checkinSessionId = checkinSessionId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBarcode() {
    return barcode;
  }
  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateValidation createValidation = (CreateValidation) o;
    return (this.scannerstationname == null ? createValidation.scannerstationname == null : this.scannerstationname.equals(createValidation.scannerstationname)) &&
        (this.checkinSessionId == null ? createValidation.checkinSessionId == null : this.checkinSessionId.equals(createValidation.checkinSessionId)) &&
        (this.barcode == null ? createValidation.barcode == null : this.barcode.equals(createValidation.barcode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.scannerstationname == null ? 0: this.scannerstationname.hashCode());
    result = 31 * result + (this.checkinSessionId == null ? 0: this.checkinSessionId.hashCode());
    result = 31 * result + (this.barcode == null ? 0: this.barcode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateValidation {\n");
    
    sb.append("  scannerstationname: ").append(scannerstationname).append("\n");
    sb.append("  checkinSessionId: ").append(checkinSessionId).append("\n");
    sb.append("  barcode: ").append(barcode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
