/**
 * flexcheckin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrganizerAuth {
  
  @SerializedName("passphrase")
  private String passphrase = null;
  @SerializedName("organizerKey")
  private String organizerKey = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPassphrase() {
    return passphrase;
  }
  public void setPassphrase(String passphrase) {
    this.passphrase = passphrase;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrganizerKey() {
    return organizerKey;
  }
  public void setOrganizerKey(String organizerKey) {
    this.organizerKey = organizerKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizerAuth organizerAuth = (OrganizerAuth) o;
    return (this.passphrase == null ? organizerAuth.passphrase == null : this.passphrase.equals(organizerAuth.passphrase)) &&
        (this.organizerKey == null ? organizerAuth.organizerKey == null : this.organizerKey.equals(organizerAuth.organizerKey));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.passphrase == null ? 0: this.passphrase.hashCode());
    result = 31 * result + (this.organizerKey == null ? 0: this.organizerKey.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizerAuth {\n");
    
    sb.append("  passphrase: ").append(passphrase).append("\n");
    sb.append("  organizerKey: ").append(organizerKey).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
