/**
 * flexcheckin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.ScannableBarcodesGroup;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Purchase {
  
  @SerializedName("reference")
  private Long reference = null;
  @SerializedName("scannableBarcodesGroups")
  private List<ScannableBarcodesGroup> scannableBarcodesGroups = null;
  @SerializedName("registrantTelephone")
  private String registrantTelephone = null;
  @SerializedName("registrantEmail")
  private String registrantEmail = null;
  @SerializedName("registrantName")
  private String registrantName = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getReference() {
    return reference;
  }
  public void setReference(Long reference) {
    this.reference = reference;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ScannableBarcodesGroup> getScannableBarcodesGroups() {
    return scannableBarcodesGroups;
  }
  public void setScannableBarcodesGroups(List<ScannableBarcodesGroup> scannableBarcodesGroups) {
    this.scannableBarcodesGroups = scannableBarcodesGroups;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRegistrantTelephone() {
    return registrantTelephone;
  }
  public void setRegistrantTelephone(String registrantTelephone) {
    this.registrantTelephone = registrantTelephone;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRegistrantEmail() {
    return registrantEmail;
  }
  public void setRegistrantEmail(String registrantEmail) {
    this.registrantEmail = registrantEmail;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRegistrantName() {
    return registrantName;
  }
  public void setRegistrantName(String registrantName) {
    this.registrantName = registrantName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Purchase purchase = (Purchase) o;
    return (this.reference == null ? purchase.reference == null : this.reference.equals(purchase.reference)) &&
        (this.scannableBarcodesGroups == null ? purchase.scannableBarcodesGroups == null : this.scannableBarcodesGroups.equals(purchase.scannableBarcodesGroups)) &&
        (this.registrantTelephone == null ? purchase.registrantTelephone == null : this.registrantTelephone.equals(purchase.registrantTelephone)) &&
        (this.registrantEmail == null ? purchase.registrantEmail == null : this.registrantEmail.equals(purchase.registrantEmail)) &&
        (this.registrantName == null ? purchase.registrantName == null : this.registrantName.equals(purchase.registrantName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.reference == null ? 0: this.reference.hashCode());
    result = 31 * result + (this.scannableBarcodesGroups == null ? 0: this.scannableBarcodesGroups.hashCode());
    result = 31 * result + (this.registrantTelephone == null ? 0: this.registrantTelephone.hashCode());
    result = 31 * result + (this.registrantEmail == null ? 0: this.registrantEmail.hashCode());
    result = 31 * result + (this.registrantName == null ? 0: this.registrantName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Purchase {\n");
    
    sb.append("  reference: ").append(reference).append("\n");
    sb.append("  scannableBarcodesGroups: ").append(scannableBarcodesGroups).append("\n");
    sb.append("  registrantTelephone: ").append(registrantTelephone).append("\n");
    sb.append("  registrantEmail: ").append(registrantEmail).append("\n");
    sb.append("  registrantName: ").append(registrantName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
