/**
 * flexcheckin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.ScannableBarcode;
import io.swagger.client.model.TicketType;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ScannableBarcodesGroup {
  
  @SerializedName("validTicketType")
  private Boolean validTicketType = null;
  @SerializedName("ticketType")
  private TicketType ticketType = null;
  @SerializedName("barcodes")
  private List<ScannableBarcode> barcodes = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getValidTicketType() {
    return validTicketType;
  }
  public void setValidTicketType(Boolean validTicketType) {
    this.validTicketType = validTicketType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public TicketType getTicketType() {
    return ticketType;
  }
  public void setTicketType(TicketType ticketType) {
    this.ticketType = ticketType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ScannableBarcode> getBarcodes() {
    return barcodes;
  }
  public void setBarcodes(List<ScannableBarcode> barcodes) {
    this.barcodes = barcodes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScannableBarcodesGroup scannableBarcodesGroup = (ScannableBarcodesGroup) o;
    return (this.validTicketType == null ? scannableBarcodesGroup.validTicketType == null : this.validTicketType.equals(scannableBarcodesGroup.validTicketType)) &&
        (this.ticketType == null ? scannableBarcodesGroup.ticketType == null : this.ticketType.equals(scannableBarcodesGroup.ticketType)) &&
        (this.barcodes == null ? scannableBarcodesGroup.barcodes == null : this.barcodes.equals(scannableBarcodesGroup.barcodes));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.validTicketType == null ? 0: this.validTicketType.hashCode());
    result = 31 * result + (this.ticketType == null ? 0: this.ticketType.hashCode());
    result = 31 * result + (this.barcodes == null ? 0: this.barcodes.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScannableBarcodesGroup {\n");
    
    sb.append("  validTicketType: ").append(validTicketType).append("\n");
    sb.append("  ticketType: ").append(ticketType).append("\n");
    sb.append("  barcodes: ").append(barcodes).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
