/**
 * flexcheckin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Status {
  
  @SerializedName("backendAlive")
  private Boolean backendAlive = null;
  @SerializedName("scannedTicketCount")
  private Long scannedTicketCount = null;
  @SerializedName("ticketCount")
  private Long ticketCount = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getBackendAlive() {
    return backendAlive;
  }
  public void setBackendAlive(Boolean backendAlive) {
    this.backendAlive = backendAlive;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getScannedTicketCount() {
    return scannedTicketCount;
  }
  public void setScannedTicketCount(Long scannedTicketCount) {
    this.scannedTicketCount = scannedTicketCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getTicketCount() {
    return ticketCount;
  }
  public void setTicketCount(Long ticketCount) {
    this.ticketCount = ticketCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Status status = (Status) o;
    return (this.backendAlive == null ? status.backendAlive == null : this.backendAlive.equals(status.backendAlive)) &&
        (this.scannedTicketCount == null ? status.scannedTicketCount == null : this.scannedTicketCount.equals(status.scannedTicketCount)) &&
        (this.ticketCount == null ? status.ticketCount == null : this.ticketCount.equals(status.ticketCount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.backendAlive == null ? 0: this.backendAlive.hashCode());
    result = 31 * result + (this.scannedTicketCount == null ? 0: this.scannedTicketCount.hashCode());
    result = 31 * result + (this.ticketCount == null ? 0: this.ticketCount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Status {\n");
    
    sb.append("  backendAlive: ").append(backendAlive).append("\n");
    sb.append("  scannedTicketCount: ").append(scannedTicketCount).append("\n");
    sb.append("  ticketCount: ").append(ticketCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
